from oop.car import Car
from oop.bus import Bus
from oop.dataProviderDictionaryCar import DataProviderDictionaryCar
from oop.motorbike import Motorbike

print("****************Car1***************")
car1 = Car(id="1", make="BMW", model="3.20i", color="Yellow", year="2018", price=180000, sunroof=True)
print("Car 1 Id     : {0}".format(car1.getId()))
print("Car 1 make   : {0}".format(car1.getMake()))
print("Car 1 model  : {0}".format(car1.getModel()))
print("Car 1 color  : {0}".format(car1.getColor()))
print("Car 1 year   : {0}".format(car1.getYear()))
print("Car 1 price  : {0}".format(car1.getPrice()))
print("Car 1 sunroof: {0}".format(car1.getSunroof()))
print("Car 1 price with tax: {0}".format(car1.calculatePriceWithTax()))

print("****************Car2***************")
car2 = Car()
car2.setId("2")
car2.setMake("Fiat")
car2.setModel("Doblo")
car2.setColor("Black")
car2.setYear("2016")
car2.setPrice(70000)
car2.setSunroof(False)

print("Car 2 Id     : {0}".format(car2.getId()))
print("Car 2 make   : {0}".format(car2.getMake()))
print("Car 2 model  : {0}".format(car2.getModel()))
print("Car 2 color  : {0}".format(car2.getColor()))
print("Car 2 year   : {0}".format(car2.getYear()))
print("Car 2 price  : {0}".format(car2.getPrice()))
print("Car 2 sunroof: {0}".format(car2.getSunroof()))
print("Car 2 price with tax: {0}".format(car2.calculatePriceWithTax()))

print("****************Bus1***************")
bus1 = Bus(id="3", make="Man", model="700C", color="Blue", year="2015", price=500000, airSuspension=True)
print("Bus 1 Id           : {0}".format(bus1.getId()))
print("Bus 1 make         : {0}".format(bus1.getMake()))
print("Bus 1 model        : {0}".format(bus1.getModel()))
print("Bus 1 color        : {0}".format(bus1.getColor()))
print("Bus 1 year         : {0}".format(bus1.getYear()))
print("Bus 1 price        : {0}".format(bus1.getPrice()))
print("Bus 1 airSuspension: {0}".format(bus1.getairSuspension()))
print("Bus 1 price with tax: {0}".format(bus1.calculatePriceWithTax()))

print("****************Bus2***************")
bus2 = Bus()
bus2.setId("4")
bus2.setMake("Man")
bus2.setModel("900C")
bus2.setColor("White")
bus2.setYear("2017")
bus2.setPrice(77000)
bus2.setairSuspension(True)

print("Bus 2 Id           : {0}".format(bus1.getId()))
print("Bus 2 make         : {0}".format(bus1.getMake()))
print("Bus 2 model        : {0}".format(bus1.getModel()))
print("Bus 2 color        : {0}".format(bus1.getColor()))
print("Bus 2 year         : {0}".format(bus1.getYear()))
print("Bus 2 price        : {0}".format(bus1.getPrice()))
print("Bus 2 airSuspension: {0}".format(bus1.getairSuspension()))
print("Bus 2 price with tax: {0}".format(bus1.calculatePriceWithTax()))

print("****************Motorbike1***************")

motorbike1 = Motorbike(id="5", make="Yamaha", model="YZF600", color="green", year="2019", price=20000,
                       selfBalance=False)
print("motorbike 1 Id         : {0}".format(motorbike1.getId()))
print("motorbike 1 make       : {0}".format(motorbike1.getMake()))
print("motorbike 1 model      : {0}".format(motorbike1.getModel()))
print("motorbike 1 color      : {0}".format(motorbike1.getColor()))
print("motorbike 1 year       : {0}".format(motorbike1.getYear()))
print("motorbike 1 price      : {0}".format(motorbike1.getPrice()))
print("motorbike 1 selfBalance: {0}".format(motorbike1.getselfBalance()))
print("motorbike 1 price with tax: {0}".format(motorbike1.calculatePriceWithTax()))

print("****************Motorbike2***************")
motorbike2 = Motorbike()
motorbike2.setId("6")
motorbike2.setMake("BMW")
motorbike2.setModel("1000C")
motorbike2.setColor("White")
motorbike2.setYear("2020")
motorbike2.setPrice(16000)
motorbike2.setselfBalance(True)

print("motorbike 2 Id         : {0}".format(motorbike2.getId()))
print("motorbike 2 make       : {0}".format(motorbike2.getMake()))
print("motorbike 2 model      : {0}".format(motorbike2.getModel()))
print("motorbike 2 color      : {0}".format(motorbike2.getColor()))
print("motorbike 2 year       : {0}".format(motorbike2.getYear()))
print("motorbike 2 price      : {0}".format(motorbike2.getPrice()))
print("motorbike 2 selfBalance: {0}".format(motorbike2.getselfBalance()))
print("motorbike 2 price with tax: {0}".format(motorbike2.calculatePriceWithTax()))

print("*********************Data Provider Dictionary Car************************")
dataProviderCar = DataProviderDictionaryCar()
dataProviderCar.insert(car1)
dataProviderCar.insert(car2)
car1.setModel("5.20i")
dataProviderCar.update(car1)
dataProviderCar.delete("1")
print(dataProviderCar.getById("2"))

print("*********************Car List************************")
carList = dataProviderCar.getList()
for carId, carInfo in carList.items():
    print(carInfo)
